### ISSUE TITLE
roadmap new release

### ISSUE THREAD

**Issue by ahms5** [ahms5/Mesh2scattering#42]
- [ ] fix history #40, #41
- [x] renew `apply_symmetry_circular` #43
- [x] renew `apply_symmetry_mirror`  #43
- [ ] add weights in json and sofa
- [ ] include new imkar implemtation of scattering and diffusion coefficient
- [ ] include all tests #32
- [ ] include all docs #12 
- [ ] remove material stuff
- [ ] include build in package #45 
- [ ] add all metadata in SOFA
- [x] fix log file name in numcalc  # 44
